[tool.poetry]
name = "hifeed"
version = "0.1.0"
description = ""
authors = ["mymindd <mypspgood@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.75.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
